# autogenerated by txs
\begin{adjustwidth}#S
\changepage{arg1}{arg2}{arg3}{arg4}{arg5}{arg6}{arg7}{arg8}{arg9}#S
\changetext{arg1}{arg2}{arg3}{arg4}{arg5}#S
\checkoddpage#S
\cplabelprefix#S
\cplabel{arg1}#S
\end{adjustwidth}#S
\newcplabel{arg1}{arg2}#S
\protect#S
\\adjustwidth#S
\changepage #S
\changetext #S
\checkoddpage #S
\cplabel#S
cpoddpagefalse#S
cpoddpagetrue#S
cpstrictfalse#S
cpstricttrue#S
ifcpoddpage#S
ifcpstrict#S
